### ISSUE TITLE
New DFM2400TSIM on address 0x60 not working.

### ISSUE THREAD

**Issue by zanco** [Theuno/PI-ATV#1]
Hi, I ordered an DFM2400TSIMB board and had the microcontroller removed from the PCB to control it from a Raspberry Pi (zero - w in this case)

An I2C python scan tool with the smbus finds the device with address 0x60, that part works, I2C has 2 pullup resistors.
The check at address 0x61 gives an error message

` [ SP5055 Controller for Raspberry PI ]
 [ by Paul Theunissen - PA5PT         ]
---------------------------
Target frequency: 2367
f: 18936
[ Sending: ]
49
f8
ce
00
Traceback (most recent call last):
  File "./atv.py", line 102, in <module>
    board.waitForLock()
  File "./atv.py", line 86, in waitForLock
    if self.readLock() == True:
  File "./atv.py", line 44, in readLock
    status = self.bus.read_byte(0x61)
IOError: [Errno 121] Remote I/O error
`

Could you help me with this ? In the end I would like to remote control a 1200 MHz receiver with the raspberry Pi for the PI6WL ATV repeater.

Thanks,
Ben - PE2BZ

**Comment by zanco** [comment]
Hi. I removed the metal case from the DFM2400TSIM module and noticed there is no SP5055 or compatible there. There is an TDA6651TT (44.25 - 866 MHz) and I assume a multiplier behind that. So the SP5055 code is not the problem.

**Comment by Theuno** [comment]
Hi Ben,
Sorry to hear that.

But there are similarities between the chips, so adjusting the code might not be too hard.
If the device is found on 0x60, I would also expect the read operation to succeed on 0x61 (page 9 of datasheet). The Frequency Lock bit is on the same location, and that is the only used value in this program.

So, I expect that the problem might be in the write operation before.

Could you change this part:
```
      a = c_ulong((f.value >> 8))
      a = c_ulong(a.value & 0x7F)
      a = chr(a.value)
      b = c_ulong(f.value & 0xFF)
      b = chr(b.value)
      # Charge pump different for some boards?
      #c = chr(0b11111110)
      c = chr(0xCE)
      d = chr(0b00000000)
```

To the example (page 46 datasheet):
```
a = chr(0x12)
b = chr(0xC0)
c = chr(0xCA)
d = chr(0xA4)
```

This tries to put the thing on 800Mhz, with the reference implementation. So it might not lock, but at least the program shouldn't fail.

Regards,
Paul - PA5PT

**Comment by zanco** [comment]
Hi Paul, thanks for your fast reply.

I changed the code as described above, however the reading from address 0x61 fails.

` [ SP5055 Controller for Raspberry PI ]
 [ by Paul Theunissen - PA5PT         ]
---------------------------
Target frequency: 2367
f: 18936
[ Sending: ]
12
c0
ca
a4
Traceback (most recent call last):
  File "./atv.py", line 96, in <module>
    board.waitForLock()
  File "./atv.py", line 80, in waitForLock
    if self.readLock() == True:
  File "./atv.py", line 42, in readLock
    status = self.bus.read_byte(0x61)
IOError: [Errno 121] Remote I/O error
`

I see no sign of the signal on 2400 MHz nor on the SDR at 800 MHz 

Thanks,
Ben

(By the way: what do you use to insert the code that nice ? )

**Comment by zanco** [comment]
Hi, Paul, did some testing this afternoon / evening. I changed the address for reading also to 0x60 to prevent the software from stopping with the Remote I/O error.

If I fire up the DFM2400 TX module with Pi connected to I2C and not running anything is tunes to about 2620 MHz . If I start the python script with your changes after about one second the TX tunes to approximately 1834 MHz so it indeed looks ok so far. 

> [ Sending: ]
12
c0
ca
a4
SP5055 Status: 148
Not yet locked
SP5055 Status: 20
Not yet locked
SP5055 Status: 20
Not yet locked

I get no clue (I am not a datasheet read and program specialist) if I can just read the lock status from the same 0x60 address. I will try to figure out how 800 MHz from the example gives TX on 1834 MHz and update the info over here.

Regards,
Ben

**Comment by zanco** [comment]
Hi, tonight I rewired the unit with the original processor. Set the TX up for 2375 MHz and with BladeRF and SDR-Console I was able to detect that the oscillator was set to 475 MHz and that is multiplied by 5 to get on 2375 MHz.

Setting the dividers to 0b 28 should give 476 MHz ( 2856 * 166,666 kHz right ?) but the TX tunes to 915 Mhz at that moment, 4 seconds after starting the Python script.

Any ideas ?
Thanks,
Ben

**Comment by Theuno** [comment]
Hi Ben,

I add code by using ` ``` ` at the beginning of a block, and at the end.

`0b 28` as divider indeed gives 2856 in value. But 4800 (0x12 0xC0) was used as reference in the datasheet to give a frequency of 800 Mhz. https://www.kynix.com/uploadfiles/pdf9675/TDA6651TT.pdf
As the IC seems to have a max frequency of 900 Mhz, I believe we should not try to convert a 2.4 Ghz value directly.

For the proper calculation we need;
* offset - guess we can assume this is 0. I believe this is used in combination with a LNB.
* divider
* multiplier
* ALBC enabled, or set the charge pump correctly. See chapter 8.1.6 of the datasheet. 

Setting this last parameter is essential. I found that newer linux kernels can have a supporting driver:
https://github.com/torvalds/linux/blob/master/drivers/media/dvb-frontends/tda665x.c

I will have a look if that is useable in some way, I never used those drivers before.

**Comment by zanco** [comment]
Hi, Paul. 
Because of the multiplying of the TX part by 5 I had to change the divider to have the TX end up in the 13 cm ATV range. 5 times 800 MHz would be to much ;-)

I did take a look on the control byte 1 (was CA in the example) and changed that to DA which would change it from  normal mode with XTOUT buffer on to fxtal (4 MHz) switch ALBC on or off[1]

control byte 2 I did change to E0 giving the charge pump the max current for High Band

No positive results yet,, the TX ends up at 2620 MHz so a bit more research is necessary

Thanks,
Ben

**Comment by zanco** [comment]
`pi@raspberrypi:~/PI-ATV $ ./atv.py
 [ TDA665x Controller for Raspberry PI ]
 [ by Paul Theunissen - PA5PT / PE2BZ  ]
---------------------------
Target frequency: 475
f: 3800
[ Sending: ]
0b
22
da
e0
TDA665x Status: 244
Locked at: 1539268929.07
`
That's the output at this moment, took me a while to understand that locked at the output had nothing to do with the frequency but represents the strftime.

My code
```
#!/usr/bin/python

# This file is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright Paul Theunissen - PA5PT

import time
import smbus
import sys
from ctypes import *

class PLL:
  #Enable/Disable debugging
  debugLib = True

  # I2C bus
  bus = smbus.SMBus(1)

  # Default frequency (2335 is PI6EHV pip3, 2367 is PI6EHV pip4)
  defFreq = 475
  lock = False
  lockTime = 0
  Xtall = c_ulong(4000)
  address = 0x60

  def __init__(self):
      print " [ TDA665x Controller for Raspberry PI ] "
      print " [ by Paul Theunissen - PA5PT / PE2BZ  ] "

  def readLock(self):
      status = self.bus.read_byte(0x60)
      print "TDA665x Status: " + str(status)
      lockBit = status & 0x40
      if lockBit == 64:
        return True
      else:
        return False

  def switchToDefaultFreq(self):
      switchToFreq(defFreq)

  def switchToFreq(self, freq):
      f = c_ulong(freq * 4 * 2)
      if self.debugLib == True:
          print "---------------------------"
          print "Target frequency: " + str(freq)
          print "f: " + str(f.value)

          a = chr(0x0b)
          b = chr(0x22)
          c = chr(0xda)
          d = chr(0xe0)
      
      if self.debugLib == True:
          print "[ Sending: ]" 
          print a.encode("hex")
          print b.encode("hex")
          print c.encode("hex")
          print d.encode("hex")

      # Send
#      values = [ord(b), ord(c)]
      values = [ord(b), ord(c), ord(d)]
      self.bus.write_i2c_block_data(self.address, ord(a), values)
      time.sleep(1)

  def waitForLock(self):
      while self.lock != True:
        if self.readLock() == True:
          self.lock = True
          self.lockTime = time.time()
          print "Locked at: " + str(self.lockTime)
          time.sleep(2)
        else:
          print "Not yet locked"
          time.sleep(2)

board = PLL()
#board.switchToDefaultFreq()
if len(sys.argv) > 1:
    print sys.argv
    board.switchToFreq(int(sys.argv[1]))
else:
    board.switchToFreq(475)
board.waitForLock()

```
It does not end up at the wanted frequency, but no error messages and a reply from the PLL :-)
